### ISSUE TITLE
 No module named 'numpy.core.multiarray\r

### ISSUE THREAD

**Issue by rsuchit123** [deepakrana47/Wheat-quality-detector-2#5] opened 2021-01-09 08:16 UTC
Traceback (most recent call last):
  File "classifier_2_v2.py", line 53, in <module>
    ftrain, y_train, ftest, y_test = pickle.load(open(feat_data, 'rb'))
ImportError: No module named 'numpy.core.multiarray\r'

I am run the code and give me this error.
I am install all the requirements with there version.
HOW can solved this error?

**Comment by deepakrana47** [comment] 2021-01-11 11:57
I will have a look into the and let you know

**Comment by deepakrana47** [comment] 2021-01-13 08:54
hello
can you try creating a separate python env for this project. You can follow the instruction given below:
1. goto code directory
2. **$ python3.5 -m venv .env**
3. **$ source .env/bin/activate**
4. **$ pip install --upgrade pip**  
5. **$ pip install opencv-python**
6. **$ pip install keras**
7. **$ pip install tensorflow**
8. **$ pip install matplotlib**
8. **$ python classifier_5_v2.py**

I am sure your problem will solve and if not we will see.

**Comment by deepakrana47** [comment] 2021-01-20 07:49
As I did not get any reply from your side. So, I am assuming that the issue is solved and closing the issue. If you still facing the problem let me know.

**Closed as completed by deepakrana47** 2021-01-20 07:49 UTC
